(feat) 100: account page
codingcommons/tiny-tms pull request #101
Opened 2024-06-23 12:29 UTC by sjaghori

#100

2024-06-30 11:41 UTC, jjnp requested changes
Really nice work!
Some more general comments on conventions, but we can have a larger discussion on those if needed. Feel free to push some of the changes off until later, in which case just make a TODO so we don't forget.

2024-06-30 11:41 UTC, jjnp commented on services/src/user/user-repository.integration.test.ts
> +		it('should return 0 when the user not exists', async () => {
I think returning 0 here is not the best way to go. I think that generally, the function should not return anything at all, since there is no value returning the user id (as it is known already). And to signify success: When there is an error, an error will be thrown, otherwise we assume success.

How we want to handle non-existing keys is a different question. imo it should be an error, but I can also be convinced that since it's an idempotent operation, we just don't do anything. The point of the function is that after calling it, there is no user with that ID. If there isn't one in the first place that is still true.

2024-06-30 11:41 UTC, jjnp commented on services/src/user/user-repository.ts
> +export function deleteUserById(id: number): Promise<DeleteResult> {
Don't return anything here. See comment on the testcase.

2024-06-30 11:41 UTC, jjnp commented on services/src/user/user-service.ts
> +	return updateResult.numUpdatedRows === 1n
Shouldn't this just throw an error if something goes wrong?
Like is there ever a case where this will return false?
Because if false indicates that something unexpected happened then it should throw an error

2024-06-30 11:41 UTC, jjnp commented on src/lib/utils/seo.ts
> +export const pageTitle = (...parts: string[]) => [...parts, 'Tiny TMS'].join(' - ')
It's nice we have it, but considering this isn't public I don't think we need seo haha

2024-06-30 11:41 UTC, jjnp commented on src/routes/(authenticated)/profile/+page.svelte
> +	const handleDeleteAccount = async () => {
Is that a feature that we need to offer? If anything I think that this would be an admin type task right?

2024-06-30 11:41 UTC, jjnp commented on src/routes/(authenticated)/profile/+page.svelte
> +	const handleUpdatePassword = async () => {
remove the `handle`. It's a direct function call after all

2024-06-30 11:41 UTC, jjnp commented on src/routes/(authenticated)/profile/+page.svelte
> +		if (newPassword !== confirmPassword) {
I we do this, then users only get feedback once they click submit. Please instead use a reactive statement to check it directly. Then the change password button is only enabled once the validation passes.
`$: showValidationError = newPassword && confirmPassword && newPassword === confirmpassword`

Validation of password security criteria should also be added, but we can leave this as a todo for later. Maybe a minimum length is enough at first.

2024-06-30 11:41 UTC, jjnp commented on src/routes/(authenticated)/profile/+server.ts
> +		}
Why differentiate here?

2024-06-30 11:41 UTC, jjnp commented on src/routes/(authenticated)/profile/+server.ts
> +		})
If you differentiate already, then we should also differentiate between zod errors and others. zod errors would be a 400

2024-06-30 11:41 UTC, jjnp commented on src/routes/(authenticated)/profile/+server.ts
> +		if (user?.id !== userId) throw Error('payload user id does not match with locals user id')
This is a clear 403 error

2024-06-30 11:41 UTC, jjnp commented on src/routes/(authenticated)/profile/+server.ts
> +		if (!result) throw new Error(`Did not delete the user, does the user ${userId} exist?`)
As in the relevant comments for this function, we should not have this check. Either it's an error and it throws one, or it isn't and we don't need to check. We should only have 1 representation for errors and imo that should be exceptions. Everything else would need to be wrapped in some sort of more explicit result object

2024-06-30 11:41 UTC, jjnp commented on src/routes/(authenticated)/profile/+server.ts
> +		return new Response(JSON.stringify({ message: 'missing user id' }), { status: 500 })
malformed request. 4xx not 500

2024-06-30 11:41 UTC, jjnp commented on src/routes/(authenticated)/profile/+server.ts
> +		})
again: 4xx error

2024-06-30 11:41 UTC, jjnp commented on src/routes/(authenticated)/profile/+server.ts
> +	}
This checking of parts of the request payload based on a zod schema and then throwing errors accordingly happens quite often. It would improve re-use and readability to extract this into a utility function

2024-06-30 11:41 UTC, jjnp commented on src/routes/(authenticated)/profile/schema.ts
> +	newPassword: z.string().min(5)
Where do these numbers come from. The 1 is clear, so it is not empty, but the 5?^^
Maybe we can have a rich validation schema that can also be re-used on the client so the users can immediately get feedback if their password matches requirements.

2024-06-30 18:27 UTC, sjaghori commented on services/src/user/user-repository.integration.test.ts
> +			const createdUser = await db.selectFrom('users').select('id').executeTakeFirstOrThrow()
I just grabbed the functions from the above tests. I agree we can be more flexible in tests and reuse other functions.

2024-06-30 18:31 UTC, sjaghori commented on services/src/user/user-repository.integration.test.ts
> +		it('should return 0 when the user not exists', async () => {
Agree, let's **not** return a 0 here. Let's throw an error here, of course we can make it idempotent, but I do not see the necessity for that.

2024-06-30 18:35 UTC, sjaghori commented on src/lib/utils/seo.ts
> +export const pageTitle = (...parts: string[]) => [...parts, 'Tiny TMS'].join(' - ')
Hahaha yes, at least we see a meaningful page title in the tab bar. :)

2024-06-30 18:37 UTC, sjaghori commented on src/routes/(authenticated)/profile/+page.svelte
> +		if (newPassword !== confirmPassword) {
Sure, good catch. Yeah let's add a todo for the validation part, I do think that we need to offer the bare minimum for the first release.

2024-06-30 18:51 UTC, sjaghori commented on src/routes/(authenticated)/profile/+page.svelte
> +	const handleUpdatePassword = async () => {
you mean the name right?

2024-06-30 18:56 UTC, sjaghori commented on src/routes/(authenticated)/profile/+server.ts
> +		if (!result) throw new Error(`Did not delete the user, does the user ${userId} exist?`)
Totally agree! Let me change that! 🚀

2024-06-30 18:57 UTC, sajaghori commented on src/routes/(authenticated)/profile/+server.ts
> +		return new Response(JSON.stringify({ message: 'missing user id' }), { status: 500 })
good catch!

2024-06-30 19:44 UTC, sajaghori commented on src/routes/(authenticated)/profile/schema.ts
> +	newPassword: z.string().min(5)
lol yes, let's go with 1 for now instead of 5 :)

2024-06-30 19:45 UTC, sjaghori commented on src/routes/(authenticated)/profile/schema.ts
> +	newPassword: z.string().min(5)
added a todo for that

2024-06-30 19:46 UTC, sjaghori commented on src/routes/(authenticated)/profile/+server.ts
> +	}
exactly, I will create another PR and then use it here.

2024-06-30 19:49 UTC, sajaghori commented on src/routes/(authenticated)/profile/+server.ts
> +		}
Here we can have Zod errors and we can also have an error thrown by the `json.parse()` function. The utility function will make it much simpler.

2024-07-02 19:55 UTC, jjnp commented on services/src/user/user-repository.integration.test.ts
> +		it('should return 0 when the user not exists', async () => {
No I also don't see the necessity for idempotency, but I mean that from an SQL perspective it would be/there is an argument why it would be okay. I agree with the error. After all deleting something that doesn't exist should usually not happen

2024-07-04 12:59 UTC, benjaminstrasser commented on services/src/user/user-repository.integration.test.ts
> +			).resolves.not.toThrowError()
nice tests!
imo we should check if the password actually changed here.

2024-07-05 18:25 UTC, sjaghori commented on services/src/user/user-repository.integration.test.ts
> +	})
good point!

2024-07-05 18:57 UTC, sjaghori commented on src/components/separator/Separator.svelte
> +<div aria-hidden="true" data-orientation="horizontal" class="h-[1px] w-full shrink-0 bg-border" />
I like that

2024-07-05 19:20 UTC, sjaghori commented on src/routes/(authenticated)/profile/+page.svelte
> +									<div class="mt-3 flex flex-col gap-3">
I'm fine with both ways. Here we would have to define multiple forms and multiple actions. 
There are situations where actions won't work. For example adapter-static or separtation of backend and frontend (sharing backend with mobile app etc.)

2024-07-11 19:22 UTC, sjaghori commented on src/routes/(authenticated)/profile/+page.svelte
> +	const handleDeleteAccount = async () => {
I would like to go ahead and offer this feature. I think it makes sense to give the user the power to delete itself. We should have a separate discussion about what an admin is supposed to do.

2024-07-12 14:47 UTC, mledl commented on src/routes/(authenticated)/profile/+page.svelte
> +	const handleDeleteAccount = async () => {
I mean we can allow it for now. Reflecting on how users were deleted from similar systems in projects I worked on, it can be said that almost every user got deleted by the admin and nobody actually took care about it himself.

2024-07-12 14:49 UTC, mledl commented on src/routes/(authenticated)/profile/+page.svelte
> +		if (newPassword !== confirmPassword) {
Ideally we release with a solid password strength validation, otherwise people might have potentially weak passwords.

2024-07-12 15:41 UTC, mledl approved these changes
Really nice work 🚀 
Jacob and Ben did a great job reviewing as well.
Some small comments and then you can merge it

2024-07-12 15:41 UTC, mledl commented on services/src/user/user-repository.ts
> +	if (!result.numDeletedRows) throw new Error('Could not delete any user')
Do you think there is a case where line 32 does not throw an error s.t. we need to check here for successful deletion again?
Same for the change password method.

2024-07-12 15:41 UTC, mledl commented on services/src/user/user-service.ts
> +import { compare, hash } from '../crypto/hash'
```suggestion
import { compare, hash } from 'services/crypto/hash'
```

2024-07-12 15:41 UTC, mledl commented on services/src/user/user-service.ts
> +	const newPasswordHash = hash(changePasswordPayload.newPassword)
Please add a TODO that states that we must add password validation.  That validation should be built in a way that we can display the issues on the client and use it for validation on server side.

2024-07-12 15:41 UTC, mledl commented on src/routes/(authenticated)/+layout.server.ts
> +	} catch (e: unknown) {
Can we pull in this try/catch into the `getUser` function?
Also I am not sure if this should be error code 500 on line 15.

2024-07-12 15:41 UTC, mledl commented on src/routes/(authenticated)/profile/+page.server.ts
> +			errorMessage = 'Cloud not update the password'
```suggestion
			errorMessage = 'Failed to update the password'
```

2024-07-12 15:48 UTC, jjnp commented on src/routes/(authenticated)/profile/+page.svelte
> +		if (newPassword !== confirmPassword) {
Agreed, but let's not be too strict here either. It should be solid, but it should not be too much. After all it's just translations and there is a good chance that for most cases it's VPN accessible only anyways.

2024-07-12 16:12 UTC, sjaghori commented on services/src/user/user-service.ts
> +import { compare, hash } from '../crypto/hash'
I have no idea why it didn't work back then and why it works now lol

2024-07-12 16:14 UTC, sjaghori commented on services/src/user/user-repository.ts
> +	if (!result.numDeletedRows) throw new Error('Could not delete any user')
deleting something that does not exit won't throw at line 32 but will throw at line 34. Jacob and I had the discussion already, I'm fine with both ways, we just need to be consistent.

2024-07-12 16:15 UTC, sjaghori commented on src/routes/(authenticated)/+layout.server.ts
> +	} catch (e: unknown) {
should the function then return undefined?

2024-07-12 16:18 UTC, sjaghori commented on src/routes/(authenticated)/+layout.server.ts
> +	} catch (e: unknown) {
And what status code is the right one? I'm also not sure, we assume that the user id exists

2024-07-12 16:39 UTC, jjnp commented on src/routes/(authenticated)/+layout.server.ts
> +	} catch (e: unknown) {
Hmm but in this situation we already checked if the user exists, that the token is valid and that the new and old passwords are okay, right?
Because in that case I'd say that it's an unexpected internal error and for that 500 is fine.

2024-07-12 16:40 UTC, jjnp commented on src/routes/(authenticated)/+layout.server.ts
> +	} catch (e: unknown) {
For the the important thing is that the error message correctly says **who** messed up. If it's the client, because the data in the request is nonsense that it's most likely not a 5xx. If the request is good, but something doesn't work out, then it's the server messing up and it's a 5xx. Or at least that's how I think of it^^

2024-07-18 19:36 UTC, benjaminstrasser commented on services/src/user/user-service.ts
> +	const newPasswordHash = hash(changePasswordPayload.newPassword)
#120

2024-07-18 19:53 UTC, benjaminstrasser approved these changes
It looks like you've implemented all the suggestions. Great job!

One remaining task that can be added to #120 is updating the change password feature. When a wrong password is entered, the error should be displayed inside the form after submission instead of just showing a toaster notification.

2024-07-19 15:07 UTC, merged