(feat) added slugs to projects
codingcommons/tiny-tms pull request #114
Opened 2024-07-10 13:34 UTC by benjaminstrasser

- added slugs to URL
- adopted tests
- wrote slug service
- added slugs to projects database schema
- adopted projects service and repository

2024-07-10 14:25 UTC, benjaminstrasser commented
One issue that still needs to be discussed.
Some generated slugs will be empty. For example ` `, `!` and so on. How do we want to deal with these?
We could simply return a invalid name error to the user. Any input?

2024-07-12 15:56 UTC, mledl commented on services/src/project/project-service.ts
> +		const slug = createSlug(project.name)
I see one problem in communicating error to the user here. Imagine a user creates a project called `Foo Bar!` and `Foo Bar !?`. Both will result into the same slug and the `CreateProjectNameNotUniqueError` to be thrown. 
It would be a better UX if we could play the error back to the user somehow.

2024-07-12 15:56 UTC, mledl commented on services/src/util/slug/slug.service.unit.test.ts
> +	})
I think empty slugs are a problem and we should only allow names that produce non empty slugs.

2024-07-15 18:17 UTC, benjaminstrasser commented on services/src/project/project-service.ts
> +		const slug = createSlug(project.name)
Added user feedback if the slug or project name is not unique inisde the form. Please check it out and give some feedback.

2024-07-19 15:09 UTC, sjaghori commented on package.json
> +		"throttle-debounce": "^5.0.2",
let's not add this. You can simply add your own debounce function

2024-07-23 12:40 UTC, benjaminstrasser commented on package.json
> +		"throttle-debounce": "^5.0.2",
Did it. I am usually a proponent of using well tested stable utility if possible, but I do see the advantages of depending on less external libs

2024-07-29 10:14 UTC, sjaghori submitted a review, later dismissed
works great! The rest also looks fine to me!

2024-08-04 08:01 UTC, sjaghori requested changes

2024-08-04 08:01 UTC, sjaghori commented on src/routes/(authenticated)/projects/+page.server.ts
> +	post: async ({ request }) => {
let's call it something more specific like `createProject`

2024-08-04 08:01 UTC, sjaghori commented on src/components/container/projects/create-project.svelte
> +		<form method="POST" action="?/post" use:enhance>
`?/createProject`

2024-08-13 18:55 UTC, sjaghori approved these changes

2024-08-13 18:56 UTC, sjaghori commented
@mledl can you approve this pr

2024-08-20 11:27 UTC, benjaminstrasser commented
@sjaghori @mledl 
This should be ready now.

2024-08-20 12:18 UTC, sjaghori approved these changes

2024-08-20 12:18 UTC, merged