Feat: Basic languages page
codingcommons/tiny-tms pull request #128
Opened 2024-08-30 16:10 UTC by mledl

This PR adds the basic languages page including the following features:

- LanguageSelect with available languages
- LanguageTable with add, delete & upsert functionality including corresponding CRUD
- Corresponding Routing

What is missing and will be done in a subsequent PR:

- E2E Testing
- Fallback language input field as select with available options
- Confirmation Modal before deleting a language

2024-09-07 12:13 UTC, sjaghori requested changes
Thank you for the PR 🚀
There are some minor issues with the validation, woud you like to have a look at that?

2024-09-07 12:13 UTC, sjaghori commented on src/components/container/language/schema.ts
> +	code: z.enum(Object.keys(availableLanguages) as [LanguageCode, ...LanguageCode[]], {
we need to give the user the ability to freely update a language code. Currently it is not possible to have language code with 'de':

<img width="1124" alt="image" src="https://github.com/user-attachments/assets/0167c56a-9fb1-471c-b667-7dfb32cda716">

2024-09-07 12:13 UTC, sjaghori commented on src/components/container/language/languages.ts
> +	'ar-ye': 'Arabic (Yemen)',
let's just go with arabic and not the localisation. We should give the user the power to add a custom localisation.

2024-09-07 12:14 UTC, sjaghori commented on src/components/container/language/schema.ts
> +	code: z.enum(Object.keys(availableLanguages) as [LanguageCode, ...LanguageCode[]], {
updating existing languages create new language in the backend. When I refresh the page, then I see the older entry

2024-09-11 18:51 UTC, mledl commented on src/components/container/language/languages.ts
> +	'ar-ye': 'Arabic (Yemen)',
Let's let them in, but we will allow the user to adapt the locale as well as you suggested in the above comment.

2024-09-11 19:02 UTC, mledl commented on src/components/container/language/schema.ts
> +	code: z.enum(Object.keys(availableLanguages) as [LanguageCode, ...LanguageCode[]], {
Did you forget to click the save button? I tested it again and with clicking save the row gets updated correctly.

2024-09-28 10:13 UTC, sjaghori approved these changes
Great job! :rocket:  I think we can merge this already.
There are just three things we should discuss:
1. IMO it makes more sense to automatically select the fallback language when a user adds a new language. It is perfectly fine to give them the option to deselect the fallback language or choose another fallback language.
2. We should consider renaming base language to default language
3. Adding a modal when there are unsaved changes or removing the save option, adding the functionality for what you see is what is in the db.

2024-09-28 10:13 UTC, sjaghori commented on src/components/container/language/languages.ts
> +	'fr-be': 'French (Belgium)',
Please also just add (fr - French), (de - German), (es - Spanish), some users might get confused when they only want to specify the language and not the country.

2024-09-28 10:30 UTC, sjaghori commented
Oh and please add a little margin of 12 to 16px between the selector and the table:

![Screenshot from 2024-09-28 12-29-10](https://github.com/user-attachments/assets/5e6fe410-605f-4569-86c2-56af25c14b51)

2024-09-29 15:12 UTC, mledl commented
> Great job! 🚀 I think we can merge this already. There are just three things we should discuss:
> 
> 1. IMO it makes more sense to automatically select the fallback language when a user adds a new language. It is perfectly fine to give them the option to deselect the fallback language or choose another fallback language.
> 2. We should consider renaming base language to default language
> 3. Adding a modal when there are unsaved changes or removing the save option, adding the functionality for what you see is what is in the db.

Will create a follow up PR for your third point. Will introduce both, improved save button state as well as the modal if there are stale changes. Moreover, I will set a the base language as fallback after creating a new language.

2024-09-29 20:46 UTC, sjaghori approved these changes

2024-09-29 20:47 UTC, merged