(feat) Sidebar
codingcommons/tiny-tms pull request #77
Opened 2024-05-31 21:43 UTC by benjaminstrasser

Added a sidebar for the authenticated section of the site.
Also added the following blank pages, which can be navigated to via the sidebar
```
/projects
/projects/[id]/keys
/projects/[id]/languages
/projects/[id]/settings
/projects/[id]/translations
```

Depends on #74

2024-06-02 13:14 UTC, jjnp approved these changes
Fine with me. We might down the line end up changing some stuff, but I don't see why we'd start predicting the future with the PR^^ Let's merge!

2024-06-02 13:21 UTC, jjnp requested changes
Gibt ein paar kleinere Issues, review folgt.

2024-06-02 16:23 UTC, benjaminstrasser commented
ran
`git rebase --onto main auth-redesign sidebar`
after #74 was merged. This no longer depends on #74

2024-06-02 19:37 UTC, sjaghori requested changes
🚀

2024-06-02 19:37 UTC, sjaghori commented on src/routes/(authenticated)/+layout.svelte
> +		$collapsedSidebar = localStorage.getItem('collapsedSidebar') === 'true'
This should not be stored in local storage, in my opinion. It should be more like an app state, and if not, then a session storage item.

2024-06-02 19:37 UTC, sjaghori commented on src/routes/(authenticated)/+layout.svelte
> +		class="sidebar duration-400 flex h-full w-80 flex-none flex-col bg-secondary text-secondary-foreground transition-all ease-in-out"
This should be splitted up into multiple components. Layout files, page files should be kept clean and easy to read IMO.

2024-06-02 19:37 UTC, sjaghori commented on src/routes/(authenticated)/projects/[id]/+layout.ts
> +	const sidebarElements = [
Let's do it in an easier way. IMO we should move this hardcoded list into the new component. Then we make a condition where we just show projects and profile when the current url is root. If we are in the projects page then we show the all the other options.

2024-06-03 14:24 UTC, benjaminstrasser commented on src/routes/(authenticated)/+layout.svelte
> +		$collapsedSidebar = localStorage.getItem('collapsedSidebar') === 'true'
I see your point. I had the same thought and initially decided against any storage. However, upon looking at Outlook, Gmail, and Confluence, I noticed that they all retain sidebar state beyond the browser session.

2024-06-03 14:26 UTC, benjaminstrasser commented on src/routes/(authenticated)/+layout.svelte
> +		class="sidebar duration-400 flex h-full w-80 flex-none flex-col bg-secondary text-secondary-foreground transition-all ease-in-out"
Agree!

2024-06-03 17:31 UTC, sjaghori approved these changes
Looks much better

2024-06-03 17:31 UTC, sjaghori commented on src/components/sidebar/sidebar.svelte
> +			My Account
this should be a button that goes to the /profile route

2024-06-03 17:31 UTC, sjaghori commented on src/routes/(authenticated)/+layout.svelte
> +	<slot></slot>
```suggestion
	<slot />
```

2024-06-03 17:31 UTC, sjaghori commented on src/routes/(authenticated)/projects/+page.svelte
> +Projects
It should automatically redirect to this page after login

2024-06-03 17:55 UTC, benjaminstrasser commented on src/routes/(authenticated)/projects/+page.svelte
> +Projects
Just a general question.
Do we have a plan for the home page?

2024-06-03 18:57 UTC, sjaghori commented on src/routes/(authenticated)/projects/+page.svelte
> +Projects
I would say let's keep the landing page out of scope for this project (a typical landing page has other stylings, components etc.). Atleast for now it is not a priority, but this can change.

2024-06-03 19:30 UTC, sjaghori commented on src/routes/(authenticated)/+layout.svelte
> +		$collapsedSidebar = localStorage.getItem('collapsedSidebar') === 'true'
It's okay, I don't mind storing a boolean in localstorage :)

2024-06-03 19:43 UTC, benjaminstrasser commented on src/routes/(authenticated)/+layout.svelte
> +		$collapsedSidebar = localStorage.getItem('collapsedSidebar') === 'true'
Will rewrite this once #81 is merged

2024-06-03 19:44 UTC, benjaminstrasser commented on src/components/sidebar/sidebar.svelte
> +			My Account
good catch!

2024-06-03 19:55 UTC, benjaminstrasser commented on src/routes/(authenticated)/projects/+page.svelte
> +Projects
I agree. The MVP should probably just redirect to /projects for now until we know what should be there.
I opened an issue #83

2024-06-03 19:57 UTC, sjaghori commented on src/routes/(authenticated)/projects/[id]/+layout.ts
> +	const sidebarElements = [
let's keep this at it is, until we decide to add the nested nav items.

2024-06-03 19:57 UTC, sjaghori submitted a review, later dismissed

2024-06-06 20:50 UTC, mledl approved these changes
Most things have been said. A really solid starting point 🚀 
Let's go with this, since things will change along the way anyways.

2024-06-06 20:50 UTC, mledl commented on src/components/sidebar/sidebar.svelte
> +				class="flex cursor-pointer rounded-lg border border-transparent p-4 hover:border-primary"
I would like to have the hover effect without the white border. Just like in the design here https://www.figma.com/design/DDkU5dnT6AsqR27sXMuRvi/Tiny-TMS?node-id=2811-11336&t=NLeByHZIV3qwCXrN-0

This will imply that we need to make the sidebar background a little darker. 
We can talk about theming anyways,

2024-06-07 11:15 UTC, mledl commented on src/components/sidebar/sidebar.svelte
> +				class="flex cursor-pointer rounded-lg border border-transparent p-4 hover:border-primary"
Alright. But I think we could merge this one, since the structure is fine.
We can then improve theming.

2024-06-07 12:44 UTC, jjnp approved these changes

2024-06-07 12:56 UTC, merged