(feat) add first and last name to user
codingcommons/tiny-tms pull request #88
Opened 2024-06-07 14:26 UTC by benjaminstrasser

In our Figma users have a first and last name.
This PR adds those fields to our user.

- [ ] update signup form
- [ ] update database
- [ ] fix services to align with new structure of users
- [ ] create a way to load user information
- [ ] load own name to display inside icon sidebar

2024-06-10 18:38 UTC, sjaghori commented on eslint.config.js
> +					ignoreRestSiblings: true
what is this?

2024-06-10 18:38 UTC, sjaghori commented on services/src/kysely/migrations/2024-04-28T09:42:38Z_init.ts
> +		.addColumn('last_name', 'text', (col) => col.notNull())
should we really force users to put both firstname and lastname? or make lastname optional?

2024-06-10 18:38 UTC, sjaghori commented on services/src/user/user-auth-service.integration.test.ts
> +			await createTestUser(newUser.email, newUser.password, newUser.role)
hashedpassword right?

2024-06-11 05:45 UTC, sjaghori requested changes

2024-06-11 05:45 UTC, sjaghori commented on src/routes/(authenticated)/+layout.server.ts
> +	const user = event.locals.user
IMO locals user should not have the password hash

2024-06-11 05:45 UTC, sjaghori commented on src/routes/(authenticated)/+layout.server.ts
> +	let loggedInUser: NonAuthUser
just `User` instead of `NonAuthUser`
For the DB, we can have UserDB type which can have all the columns.

2024-06-11 05:45 UTC, sjaghori commented on src/components/sidebar/sidebar.svelte
> +			{#if userData === undefined}
```suggestion
			{#if !userData}
```

2024-06-11 10:08 UTC, benjaminstrasser commented on eslint.config.js
> +					ignoreRestSiblings: true
`const { password_hash, ...nonAuthUser } = user`, would cause an unused variable error otherwise.
Alternatively, we could use `delete` or simply move all other properties like this:
```
const nonAuthUser = {
    name: user.name,
    other: user.other,
    // exclude unwanted prop
}
```

2024-06-11 10:09 UTC, benjaminstrasser commented on services/src/kysely/migrations/2024-04-28T09:42:38Z_init.ts
> +		.addColumn('last_name', 'text', (col) => col.notNull())
I would prefer to keep them mandatory for now. I think we may have to revisit signup at some point anyway.

2024-06-11 10:13 UTC, benjaminstrasser commented on services/src/user/user-auth-service.integration.test.ts
> +			await createTestUser(newUser.email, newUser.password, newUser.role)
This was a mistake as `register` is supposed to be called here. Good catch!

2024-06-11 10:14 UTC, benjaminstrasser commented on src/routes/(authenticated)/+layout.server.ts
> +	const user = event.locals.user
Yeah definitely. Good catch!

2024-06-11 11:50 UTC, benjaminstrasser commented on src/routes/(authenticated)/+layout.server.ts
> +	const user = event.locals.user
Currently does not contain the password hash or am i missing something?

2024-06-11 11:51 UTC, benjaminstrasser commented on src/routes/(authenticated)/+layout.server.ts
> +	let loggedInUser: NonAuthUser
Agree!
Will change this in the next commit

2024-06-14 09:28 UTC, sjaghori requested changes

2024-06-14 09:28 UTC, sjaghori commented on eslint.config.js
> +					ignoreRestSiblings: true
You could add a utility for this right? https://stackoverflow.com/a/56773391

2024-06-14 09:28 UTC, sjaghori commented on services/src/user/user-service.ts
> +	return nonAuthUser as User
no casting please, there are better ways :)

2024-06-14 09:28 UTC, sjaghori commented on src/routes/(authenticated)/+layout.ts
> +		...data,
let's be explicit here

2024-06-16 11:07 UTC, sjaghori commented on src/routes/(authenticated)/+layout.server.ts
> +	const user = event.locals.user
yes you are right.

2024-06-16 11:34 UTC, benjaminstrasser commented on src/routes/(authenticated)/+layout.ts
> +		...data,
done. great catch!

2024-06-16 11:37 UTC, sjaghori approved these changes
🚀

2024-06-16 11:39 UTC, merged